/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

// Skip waiting phase and activate the new service worker as soon as it's finished installing
self.addEventListener('install', () => {
  self.skipWaiting();
});

// Claim any clients immediately so that the page will be under the control of the new service worker
clientsClaim();

// Clean up old caches that are no longer needed
cleanupOutdatedCaches();

// Precache assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Handle navigation requests: serve the application shell from the network first, fallback to cache
const navigationRoute = new NavigationRoute(
  new NetworkFirst({
    cacheName: 'app-shell',
    networkTimeoutSeconds: 5,
    plugins: [],
  })
);

registerRoute(navigationRoute);

// Optionally, add runtime caching for API requests or other resources
// Example: Cache API responses with a stale-while-revalidate strategy
/*
registerRoute(
  ({ url }) => url.origin === 'https://api.example.com',
  new StaleWhileRevalidate({
    cacheName: 'api-cache',
    plugins: [],
  })
);
*/

// Listen to push events (if you plan to use push notifications)
/*
self.addEventListener('push', (event) => {
  const data = event.data?.json() || {};
  event.waitUntil(
    self.registration.showNotification(data.title, {
      body: data.body,
      icon: data.icon,
    })
  );
});
*/
